# Домашняя работа 1.2

__Задание 1. Генератор случайных матриц.__

Реализовать генератор матриц, который должен поддерживать функции:
* Генерация абсолютно случайной матрицы $n\times m$
* Генерация случайной диагональной матрицы $n\times n$
* Генерация случайной верхнетреугольной матрицы
* Генерация случайной нижнетреугольной матрицы
* Генерация симметричной матрицы
* Генерация возмущения матрицы $n\times m$, каждый элемент которой не превосходит по модулю заданный $\varepsilon$. Оценить величину нормы матрицы возмущений в зависимости от параметра $\varepsilon$ (оценить верхную границу).

Оценить численно вероятность того, что созданная матрица будет вырожденной для какого-либо случая выше.

In [1]:
import numpy as np

In [2]:
# Изначально реализована произвольная m,n, верхнетреугольная и симметричная.

import numpy as np

def matrix_generate(rows, columns, type_ = "full", eps = 0):
    """
    matrix_generate(rows, columns, type_ = "full") - 
    создаёт случайную матрицу выбранного типа.

    Если матрицу нужных размеров создать нельзя, должен выдать
    строку f"Error with type {type_} and shape ({rows},{columns})".

    Parameters
    ----------

    rows : int
        Количество строк в создаваемой матрице.
    columns : int
        Количество столбцов в создаваемой матрице.
    type_ : str, optional
        Тип создаваемой матрицы: "full", "upper_triangular", "symmetric" и т.д.
    eps: float, optional
        Дополнительное число, использующееся при генерации для некоторых типов матриц.

    Returns
    -------
    out : ndarray or str
        Выдаёт матрицу нужного типа либо ошибку.

    Notes
    -----
    Поддерживаемые типы матриц:
        "full","upper_triangular",
        "symmetric",
        ...


    """

    A = None

    #в зависимости от типа A генерируется матрица
    
    if type_ == "full": #обычная 

        A = np.random.random(size=(rows, columns))

    elif type_ == "upper_triangular": #верхне-треугольная. Элементы ниже диагонали - 0

        A = np.random.random(size=(rows, columns))

        for i in range(rows):
            for j in range(columns):
                if (i > j):
                    A[i, j] = 0
                    
    elif type_ == "lower_triangular": #нижне-треугольная. Аналогично, элементы выше диагонаи - 0. 

        A = np.random.random(size=(rows, columns))

        for i in range(rows):
            for j in range(columns):
                if (i < j):
                    A[i, j] = 0


    elif type_ == "symmetric": #симметричная. 

        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"

        else:
            A = np.random.random(size=(rows, columns))

            for i in range(rows):
                for j in range(columns): #происходит симметризация
                    if (i > j):
                        A[i, j] = A[j, i]

    
    elif type_ == "diagonal": #диагональная 

        if rows != columns:
            return f"Error with type {type_} and shape ({rows},{columns})"

        else:

            A = matrix_generate(rows, columns, "upper_triangular") 

            for i in range(rows): #обнуление выше элементов главной диагонали в верхне-треугольной
                for j in range(columns):
                    if (i < j):
                        A[i, j] = 0

    return A

In [3]:
matrix_generate(1, 3)

array([[0.42751309, 0.41015284, 0.54123656]])

In [4]:
matrix_generate(4, 4, type_ = "upper_triangular")

array([[0.05047808, 0.75728261, 0.78821725, 0.57072573],
       [0.        , 0.62138737, 0.48189442, 0.61707544],
       [0.        , 0.        , 0.36180403, 0.2380998 ],
       [0.        , 0.        , 0.        , 0.10089974]])

In [5]:
matrix_generate(4, 3, type_ = "upper_triangular")

array([[0.55408298, 0.26707979, 0.44870037],
       [0.        , 0.29223687, 0.26379933],
       [0.        , 0.        , 0.61104579],
       [0.        , 0.        , 0.        ]])

In [6]:
matrix_generate(4, 4, type_ = "symmetric")

array([[0.62611614, 0.08475432, 0.50287215, 0.96827079],
       [0.08475432, 0.59225126, 0.74683443, 0.66888759],
       [0.50287215, 0.74683443, 0.21374388, 0.83040656],
       [0.96827079, 0.66888759, 0.83040656, 0.6793492 ]])

In [7]:
matrix_generate(4, 4, type_ = "diagonal")

array([[0.95304109, 0.        , 0.        , 0.        ],
       [0.        , 0.57338355, 0.        , 0.        ],
       [0.        , 0.        , 0.25877529, 0.        ],
       [0.        , 0.        , 0.        , 0.47810921]])

In [8]:
matrix_generate(4, 4, type_ = "lower_triangular")

array([[0.36808379, 0.        , 0.        , 0.        ],
       [0.38095561, 0.31731024, 0.        , 0.        ],
       [0.96919144, 0.13856189, 0.61861   , 0.        ],
       [0.01508507, 0.84505535, 0.80023656, 0.09623441]])

Посчитаем вероятность получить вырожденную диагональную матрицу. Эта вероятность равна нулю.

__Задание 2. Вычисление матричных норм и числа обусловленности.__

Реализовать вычисление трех основных норм векторов (L1, L2 и максимальную) и подчиненных им матричных норм. Реализовать вычисление числа обусловленности.

Примечание: для вычисления собственных значений можно использовать linalg.eigvals из модуля scipy.

In [13]:
def NormVector(vector_, size, type_ = "L_2"):

  NormVector = 0 #эта функция вычисляет норму вектора

  if (type_ == "L_1"): #вычисление нормы L1

    for i in range(size):

      NormVector += abs(vector_[i])

  elif (type_ == "L_2"): # Вычисление нормы L2

    for i in range(size):

      NormVector += vector_[i]**2
    NormVector = NormVector**0.5

  elif (type_ == "max"): # Вычисление максимальной нормы
    for i in range(size):
      if (NormVector < abs(vector_[i])):
        NormVector = abs(vector_[i])

  return NormVector

def NormMatrix(matrix_, rows, columns, type_ = "L_2"):

  NormMatrix = 0 #эта функция вычисляет норму матрицы, соответсвующих норм вектора

  if (type_ == "L_1"): #максимальная сумма модулей элементов в столбце
    time = 0
    for j in range(columns):
      for i in range(rows):
        time += abs(matrix_[i,j])
      if (time > NormMatrix):
        NormMatrix = time
      time = 0


  elif (type_ == "L_2"): #\sqrt(\lambda (A^T A))
    new = np.dot(matrix_.T, matrix_) #находим список собственных векторов произведения матрицы на транспонированную
    lambds = np.linalg.eigvals(new) 
    NormMatrix = (max(lambds)) ** 0.5

  elif (type_ == "max"): #максимальная сумма модулей элементов в строке
    time = 0
    for i in range(rows):
      for j in range(columns):
        time += abs(matrix_[i,j])
      if (time > NormMatrix):
        NormMatrix = time
      time = 0


  return NormMatrix

In [14]:
A = [1, 0, 3, -6] #проверяем NormVector
print(NormVector(A, 4,"L_2"))
print(NormVector(A, 4,"L_1"))
print(NormVector(A, 4,"max"))

6.782329983125268
10
6


In [15]:
A = matrix_generate(4, 3) #проверяем NormMatrix
print(NormMatrix(A, 4, 3, "L_2"))
print(NormMatrix(A, 4, 3, "L_1"))
print(NormMatrix(A, 4, 3, "max"))

2.0322986119948188
2.9503945316254443
1.8684669816513377


Теперь реализуем вычисление числа обусловленности матрицы A

In [16]:
def NumCon(matrix_, rows, columns, type_ = "L_2"):
  NumCon = 0
  if type_ == "L_1":
    A_1 = np.linalg.inv(A) #обратная матрица
    NormA = NormMatrix(A, rows, columns, "L_2") #норма матрицы для l2
    NormA_1 = NormMatrix(A_1, rows, columns, "L_2") #норма обратной матрицы для L2
    NumCon = NormA * NormA_1 #число обусловленности
  elif type_ == "L_1":
    A_1 = np.linalg.inv(A) #аналогично
    NormA = NormMatrix(A, rows, columns, "L_1")
    NormA_1 = NormMatrix(A_1, rows, columns, "L_1")
    NumCon = NormA * NormA_1
  elif type_ == "max":
    A_1 = np.linalg.inv(A)
    NormA = NormMatrix(A, rows, columns, "max")
    NormA_1 = NormMatrix(A_1, rows, columns, "max")
    NumCon = NormA * NormA_1
  return NumCon

In [17]:
A = matrix_generate(3, 3) #проверяем NumCon
print(NumCon(A, 3, 3, "L_2"))
print(NumCon(A, 3, 3, "L_1"))
print(NumCon(A, 3, 3, "max"))

0
104.86711112853251
160.88863772074225


__Задание 3. Эквивалентность первых двух норм.__

Найдите константы $C_1$  и  $C_2$ такие, что

$\ C_1||\mathbf{x}||_2\leq||\mathbf{x}||_1\leq C_2||\mathbf{x}||_2$


Указание: в качестве подсказки можно использовать визуализацию норм из документа с теорией.

Сначала найдем $C_2$ \\
$$C_2 \geq \frac{||x||_1}{||x||_2} = \frac{\sum |x_i|}{(\sum x_i^2)^{\frac{1}{2}}} \geq \frac{\sum |x|_{min}}{(\sum x_{max}^2))^{\frac{1}{2}}} = \sqrt n \frac{|x|_{min}}{|x|_{max}}$$


Теперь найдем $C_1$ \\
$$C_1 \leq \frac{||x||_1}{||x||_2} = \frac{\sum |x_i|}{(\sum x_i^2)^{\frac{1}{2}}} \leq \frac{\sum |x|_{max}}{(\sum x_{min}^2)^{\frac{1}{2}}} = \sqrt n \frac{|x|_{max}}{|x|_{min}}$$

__Задание 4. Евклидова и бесконечная норма.__

 Пусть x — вектор размерности m, а A — матрица m×n. Докажите следующие неравенства и приведите
примеры таких x и A, при которых неравенства обращаются в равенства:

- $\|x\|_2 \leq \sqrt{m} \cdot \|x\|_{\infty}$
- $\|A\|_{\infty} \leq \sqrt{n} \cdot \|A\|_2$

Докажем первое неравнество $\|x\|_2 \leq \sqrt{m} \cdot \|x\|_{\infty}$ \\
$$||x||_2 = (\sum x_i^2)^{\frac{1}{2}} \leq (\sum x_{max}^2)^{\frac{1}{2}} = (m*x_{max})^{\frac{1}{2}} = \sqrt m ||x||_{∞}$$

Докажем второе неравенство $\|A\|_{\infty} \leq \sqrt{n} \cdot \|A\|_2$ \\
$$$$ (неравенство Коши-Буняковского)

$$ \|A\|_{\infty} = \max_i \sum_j \left| a_{ij} \right| \leq \sqrt{\sum_i \left( \sum_j \left| a_{ij} \right| \right)^2} \leq \sqrt{n \sum_i \sum_j \left| a_{ij} \right|^2} = \sqrt{n} \cdot \|A\|_2 $$


__Задание 5.  Норма Фробениуса.__

Докажите, что для любой унитарной матрицы U (и для произвольной матрицы A) имеет место равенство

 $\| U A \|_F = \| AU \|_F = \| A \|_F$ ,

 где $\| \cdot \|_F$ — норма Фробениуса.

Указание.  
Задачу можно решить без вычислений, если использовать геометрический смысл нормы Фробениуса и геометрические свойства умножения на унитарную матрицу (что при умножении на неё сохраняется). \\

Решение:

(норма Фробениуса - корень из суммы квадратов всех элементов квадратной матрицы. 
Унитарная U U* = U* U= E, эрмитово U* - транспонированная + комплексно сопряженная)

Рассмотрим мартрицу A как совокупность векторов-столбцов:
$$A = (a_1, ... a_n)$$ \\
Тогда $$||QA||_F^2 = ||Qa_1,...,Qa_n||_F^2 = ||(c_1, ..., c_n)||_F^2 = ∑ \sum c_{ij}^2 = \sum (c_i, c_i) = \sum ||c_i||_2^2 = \sum (a_i, a_i) =  ||A||_F^2$$ \\
где $c_i = Qa_i$ и $||c_i||_2 = ||Qa_i|| = ||a_i||$, поскольку умножене ортогональной матрицы на вектор не меняет евклидову длину этого вектора.
Теперь покажем, что сферическая норма матрицы не меняется и в результате умножения ее на ортогональную матрицу Q справа: \\
$$||AQ||_F = ||(AQ)^T||_F = ||Q^TA^T||_F = ||A^T||_F = ||A||_F$$